# Generated by Django 3.2.12 on 2022-07-13 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('rut', models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='rut')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('correo', models.CharField(max_length=50, verbose_name='correo')),
                ('telefono', models.CharField(max_length=15, verbose_name='telefono')),
                ('direccion', models.CharField(max_length=30, verbose_name='direccion')),
                ('password1', models.CharField(blank=True, max_length=20, null=True, verbose_name='password1')),
                ('password2', models.CharField(blank=True, max_length=20, null=True, verbose_name='password2')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id del Producto')),
                ('nombre', models.CharField(max_length=20, verbose_name='Nombre')),
                ('precio', models.IntegerField(verbose_name='Precio')),
                ('descripcion', models.CharField(max_length=40, verbose_name='Descripcion')),
                ('imagen', models.ImageField(upload_to='productos')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('rut', models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='rut')),
                ('contraseña', models.CharField(blank=True, max_length=20, null=True, verbose_name='contraseña')),
            ],
        ),
    ]
