# Generated by Django 3.2.12 on 2022-07-13 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='password1',
            field=models.CharField(max_length=20, verbose_name='password1'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='password2',
            field=models.CharField(max_length=20, verbose_name='password2'),
        ),
    ]
