# Generated by Django 3.2.13 on 2022-07-15 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_producto_idproducto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
