# Generated by Django 3.2.12 on 2022-06-28 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20220628_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='rut',
            field=models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='rut'),
        ),
    ]
