# Generated by Django 3.2.12 on 2022-07-12 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_cliente_rut'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='contraseña',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='contraseña'),
        ),
    ]
